import type { ColorMap } from "@/lib/types";

// Generated by farthest-point sampling in OKLab space (greedy: each color
// maximizes the minimum perceptual distance to every color already picked),
// so nearby indices never land on near-identical hues the way a hand-picked
// list can. Order matters: earlier slots are the most mutually distinct.
export const ROUTE_COLORS = [
  "#6e5dd8", "#66a70c", "#b93000", "#db5dab", "#0da2c6",
  "#047745", "#c38238", "#9d2c89", "#0369a1", "#9e80d1",
  "#e55454", "#827f11", "#4f8eff", "#199d78", "#ad536e",
  "#a550be", "#744f99", "#a7611b", "#238c0a", "#0a72da",
  "#b02053", "#0685b6", "#a09600", "#697ac8", "#b069a5",
  "#cf7187", "#4158bd", "#bf4392", "#e66700", "#c267d4",
  "#5b6c00", "#8477f3", "#c36a51", "#9c4245", "#c8384b",
  "#669649", "#d94c7c", "#8c66b2", "#93436f", "#6c45bd",
  "#c94e0c", "#22ad61", "#9b4801", "#8838a8", "#4591d7",
  "#6564b2", "#3d8749", "#984d98",
];

export function getRouteColor(index: number): string {
  return ROUTE_COLORS[index % ROUTE_COLORS.length];
}

export function buildColorMap(routes: { id: string }[]): ColorMap {
  const map: ColorMap = {};
  routes.forEach((r, i) => {
    map[r.id] = getRouteColor(i);
  });
  return map;
}
